[workspace]

members = [
    "nllm_plane",
    "nllm_embed",
    "nllm_respond",
    "nllm_chat_web",
    "nllm_chat_functions",
]

# TODO: consider removing - disabled to prevent large binaries pushed to s3
# [profile.release]
# debug = true