[package]
name = "plane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
js-sys = "0.3.61"
plotly = { version = "0.8.3", features = ["wasm"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
wasm-bindgen = "0.2.84"
web-sys = { version = "0.3.61", features = ["HtmlCanvasElement"] }
yew = { version = "0.20.0", features = ["csr"] }
yew-hooks = "0.2.0"

[dev-dependencies]
rand = { version = "0.8.5" }

[features]
default = []
short_floats = []
